from pymongo import MongoClient
import time

client = MongoClient("mongodb://localhost:27017/")
db = client["benchmark"]
collection = db["test"]

collection.delete_many({})

num_records = 100000
data = {"value": "a" * 1024}  # 1KB data with all 'a'

start_time = time.time()

# _id of each document will be generated by MongoDB
for _ in range(num_records):
    collection.insert_one(data.copy())

end_time = time.time()
total_time = end_time - start_time
tps = num_records / total_time

# print(f"Total time: {total_time:.2f} seconds")
print(f"MongoDB TPS: {tps:.2f}")
print(f"Average latency: {(total_time/num_records)*1000:.2f} ms")

client.close()
